import turtle
s= turtle.getscreen()
turtle.ht()
t1=turtle.Turtle()
t1.ht()
turtle.bgcolor("black")
t1.pencolor("red")
t1.fillcolor("yellow")
t1.shape("arrow")
t1.shapesize(5,5,5)
t1.speed(1000)
for r in range (200):
        t1.rt(50)
        t1.fd(r)
        t1.pencolor("goldenrod")
        t1.rt(60)
        t1.fd(r)
        t1.pencolor("red")
        t1.rt(70)
        t1.fd(r)
        t1.pencolor("blue")
        t1.rt(60)
        t1.fd(r)
        t1.pencolor("white")
        t1.rt(50)
        t1.fd(r)
        t1.pencolor("darkgreen")
        t1.rt(40)
        t1.fd(r)
        t1.pencolor("darkviolet")
        
input()